# Generated by Django 4.0.4 on 2022-05-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='image_title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='image_description')),
                ('time_uploaded', models.DateTimeField(verbose_name='upload_time')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
