# Generated by Django 4.0.4 on 2022-05-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_repo', '0002_image_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time_uploaded',
            field=models.DateTimeField(default='2022-05-19-23-31-17', verbose_name='upload_time'),
        ),
    ]
