# Generated by Django 4.0.4 on 2022-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_repo', '0013_image_owner_alter_image_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='image',
            name='time_uploaded',
            field=models.DateTimeField(default='2022-05-20 19:18:10', verbose_name='Upload Time'),
        ),
    ]
