# Generated by Django 4.0.4 on 2022-05-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_repo', '0017_rename_visibility_image_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time_uploaded',
            field=models.DateTimeField(default='2022-05-20 19:50:04', verbose_name='Upload Time'),
        ),
    ]
